[[rulesets]]
group = "DIRECT"
ruleset = "rules/LocalAreaNetwork.list"

[[rulesets]]
group = "Microsoft"
ruleset = "rules/MSServices.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/DivineEngine/Surge/Ruleset/Unbreak.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://api.onedrive.com/v1.0/shares/s!AvmkyhMlHpv8i8YlJbr45h4ZpV3SOQ/root/content"

[[rulesets]]
group = "DIRECT"
ruleset = "clash-domain:https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/direct.txt"

[[rulesets]]
group = "广告拦截"
ruleset = "rules/NobyDa/Surge/AdRule.list"

[[rulesets]]
group = "广告拦截"
ruleset = "rules/NobyDa/Surge/AdRule.list"

[[rulesets]]
group = "运营劫持"
ruleset = "rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list"

[[rulesets]]
group = "NETFLIX"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list"

[[rulesets]]
group = "巴哈姆特"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list"

[[rulesets]]
group = "国外媒体"
ruleset = "rules/DivineEngine/Surge/Ruleset/StreamingMedia/Streaming.list"

[[rulesets]]
group = "哔哩哔哩"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Bilibili.list"

[[rulesets]]
group = "哔哩哔哩"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Bilibili.list"

[[rulesets]]
group = "TikTok"
ruleset = "https://raw.githubusercontent.com/Semporia/TikTok-Unlock/master/Loon/TikTok.list"

[[rulesets]]
group = "国内媒体"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/iQiyi.list"

[[rulesets]]
group = "国内媒体"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Letv.list"

[[rulesets]]
group = "国内媒体"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/MOO.list"

[[rulesets]]
group = "国内媒体"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Tencent Video.list"

[[rulesets]]
group = "国内媒体"
ruleset = "rules/lhie1/Surge/Surge 3/Provider/Media/Youku.list"

[[rulesets]]
group = "Telegram"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Telegram/Telegram.list"

[[rulesets]]
group = "Proxy"
ruleset = "https://api.onedrive.com/v1.0/shares/s!AvmkyhMlHpv8valmU8Y1gSJet0UwUg/root/content"

[[rulesets]]
group = "Proxy"
ruleset = "rules/DivineEngine/Surge/Ruleset/Global.list"

[[rulesets]]
group = "Apple"
ruleset = "rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/DivineEngine/Surge/Ruleset/China.list"

[[rulesets]]
group = "DIRECT"
ruleset = "rules/NobyDa/Surge/Download.list"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/zer4tul/now-subconverter/master/subconverter/rules/DirectConnectDomains.list"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "Final"
ruleset = "[]FINAL"

